import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.argv[2]||'http://127.0.0.1:4411',site=process.argv[3]||'http://127.0.0.1:4311/';
const tag=base.includes('4411')?'local':'production';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1600,height:1000},deviceScaleFactor:1,acceptDownloads:true});
const page=await context.newPage();const errors=[];
const sceneView=page.locator('[data-editor-route="/scene-editor"].is-visible'),assetView=page.locator('[data-editor-route="/asset-editor"].is-visible'),experienceView=page.locator('[data-editor-route="/path-editor"].is-visible');const evidence={base,site};
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,300))});
try{
 await page.goto(base+'/review?site='+encodeURIComponent(site));
 await page.locator('.review-logo-open-editor').click({timeout:45000});
 await page.getByRole('navigation',{name:'Review workspace'}).waitFor({timeout:15000});
 await page.waitForTimeout(1500);
 const hint=page.getByRole('button',{name:'Turn off hints',exact:true});if(await hint.isVisible())await hint.click();
 evidence.connectedUrl=page.url();
 evidence.captureFrames=[];
 for(const frame of page.frames().slice(1))evidence.captureFrames.push(await frame.evaluate(()=>({url:location.href,ready:window.__kageReview?.ready,actors:window.__kageReview?.records.length,anchors:window.__kage?.anchors(),buildId:window.__kageReview?.buildId})).catch(e=>String(e)));
 await page.getByRole('link',{name:'Scene',exact:true}).click();await sceneView.waitFor({state:'visible',timeout:25000});await page.waitForTimeout(900);
 await sceneView.getByRole('button',{name:'Tree',exact:true}).click();
 await sceneView.locator('.object-select').filter({hasText:'Torii gate'}).dblclick({timeout:5000}).catch(()=>{});
 await page.waitForTimeout(500);
 await page.screenshot({path:`.evidence/${tag}-scene.png`});evidence.sceneText=(await page.locator('body').innerText()).slice(0,10000);
 await page.getByRole('link',{name:'Asset',exact:true}).click();
 await assetView.waitFor({state:'visible',timeout:35000});
 const assetTree=assetView.getByRole('button',{name:'Tree',exact:true});if(await assetTree.getAttribute('aria-expanded')!=='true')await assetTree.click();
 await assetView.locator('.asset3d-asset-select').filter({hasText:'Torii gate'}).click({timeout:25000});
 await page.waitForTimeout(3500);
 await page.screenshot({path:`.evidence/${tag}-torii.png`});evidence.assetText=(await page.locator('body').innerText()).slice(0,12000);
 const details=assetView.getByRole('button',{name:'Details',exact:true});if(await details.getAttribute('aria-expanded')!=='true')await details.click();
 await assetView.getByRole('button',{name:'Add asset observation'}).click();
 const note='Disposable integration check: preserve the weathered lacquer and swept kasagi; source buildTorii.';
 await assetView.getByPlaceholder('What should change about the asset as a whole?').fill(note);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Feedback JSON'}).click();const d=await download;await d.saveAs(`.evidence/${tag}-feedback.json`);
 const feedback=JSON.parse(await fs.readFile(`.evidence/${tag}-feedback.json`,'utf8'));
 assert(JSON.stringify(feedback).includes('kage-torii'));assert(JSON.stringify(feedback).includes('index.html#buildTorii'));evidence.feedback=feedback;
 await page.reload();await page.getByRole('navigation',{name:'Review workspace'}).waitFor({timeout:45000});
 await assetView.waitFor({state:'visible',timeout:35000});
 const refreshedDetails=assetView.getByRole('button',{name:'Details',exact:true});if(await refreshedDetails.getAttribute('aria-expanded')!=='true')await refreshedDetails.click();
 await assetView.getByPlaceholder('What should change about the asset as a whole?').waitFor({timeout:15000});
 assert.equal(await assetView.getByPlaceholder('What should change about the asset as a whole?').inputValue(),note);evidence.refreshPreserved=true;
 await page.getByRole('link',{name:'Experience',exact:true}).click();await experienceView.waitFor({state:'visible',timeout:35000});await page.waitForTimeout(1200);
 await experienceView.getByRole('button',{name:'Stop 1: Arrival',exact:true}).click();
 await experienceView.getByRole('button',{name:'Play journey',exact:true}).click();await page.waitForTimeout(500);await experienceView.getByRole('button',{name:'Pause journey',exact:true}).click();
 await page.screenshot({path:`.evidence/${tag}-experience.png`});evidence.experienceText=(await experienceView.innerText()).slice(0,14000);
 console.log(JSON.stringify({connectedUrl:evidence.connectedUrl,captureFrames:evidence.captureFrames,refreshPreserved:evidence.refreshPreserved,assetText:evidence.assetText?.slice(-2500),experienceText:evidence.experienceText?.slice(-4000),failure:evidence.failure,body:evidence.body?.slice(0,3500)}));
}catch(error){evidence.failure=String(error);evidence.body=(await page.locator('body').innerText()).slice(0,7000);await page.screenshot({path:`.evidence/${tag}-failure.png`});console.log(JSON.stringify({connectedUrl:evidence.connectedUrl,captureFrames:evidence.captureFrames,refreshPreserved:evidence.refreshPreserved,assetText:evidence.assetText?.slice(-2500),experienceText:evidence.experienceText?.slice(-4000),failure:evidence.failure,body:evidence.body?.slice(0,3500)}));process.exitCode=1;
}finally{await fs.writeFile(`.evidence/${tag}-editor.json`,JSON.stringify({...evidence,errors},null,2));await browser.close();}
